# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 19:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name=datetime.datetime(2017, 6, 10, 19, 47, 0, 360980))),
                ('title', models.CharField(max_length=256)),
                ('body', models.TextField()),
                ('upload', models.FileField(null=True, upload_to=b'')),
            ],
        ),
    ]
