# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 20:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 6, 10, 20, 7, 18, 459457))),
                ('title', models.CharField(max_length=256)),
                ('body', models.TextField()),
                ('upload', models.FileField(null=True, upload_to=b'')),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
