# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 01:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170610_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 11, 1, 46, 41, 646843)),
        ),
    ]
