# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 03:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170611_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 11, 3, 3, 4, 438132)),
        ),
    ]
